
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - relationships:
                    to: ref('my_first_dbt_model')
                    field: id

    - name: playing_with_tests
      description: "A customer dataset"
      columns:
          - name: c_custkey
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
          - name: name
            description: "First initial"
            tests:
              - accepted_values:
                  values:
                    - 'A.'
                    - 'B.'
                    - 'C.'
                    - 'D.'
                    - 'E.'
                    - 'F.'
                    - 'G.'
                    - 'H.'
                    - 'I.'
                    - 'J.'
                    - 'K.'
                    - 'L.'
                    - 'M.'
                    - 'N.'
                    - 'O.'
                    - 'P.'
                    - 'Q.'
                    - 'R.'
                    - 'S.'
                    - 'T.'
                    - 'W.'

    - name: cumulative_orders_by_date
      description: "Running cumulative payments by order date"
      columns:
          - name: orderid
            description: "Order id"
          - name: order_date
            description: "Order date"
          - name: paymentid
            description: "Payment id"
          - name: amountpd
            description: "Payment amount"
          - name: runningtotal
            description: "Cumulative payments made for orders placed on or before the order date"
          - name: paymentid
            tests:
                - unique
                - not_null
          - name: amountpd
            tests:
                - not_null
          - name: order_date
            tests:
                - not_nullsources:
  - name: sample2
    schema: dbt
    tables:
      - name: snowflake_customer_purchases
  - name: sample3
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders
